apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  selector:
    matchLabels:
      app: php-app
  replicas: 2
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: 471112907684.dkr.ecr.ap-south-1.amazonaws.com/rajack:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: php-app
spec:
  selector:
    app: php-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
